-- Roles / permisos (RBAC) para Supabase (schema public).
-- Nota: La creacion de usuarios de Auth NO debe hacerse desde el cliente.
-- Para crear usuarios desde el sistema, use una Edge Function / API con SERVICE_ROLE.

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.role, '')) = 'administrador'
  );
$$;

create table if not exists public.app_roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_permissions (
  key text primary key,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_role_permissions (
  role_id bigint not null references public.app_roles(id) on delete cascade,
  perm_key text not null references public.app_permissions(key) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, perm_key)
);

create table if not exists public.app_user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id bigint not null references public.app_roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

alter table public.app_roles enable row level security;
alter table public.app_permissions enable row level security;
alter table public.app_role_permissions enable row level security;
alter table public.app_user_roles enable row level security;

-- Lectura general (usuarios autenticados).
drop policy if exists "app_roles_read" on public.app_roles;
create policy "app_roles_read"
on public.app_roles
for select
to authenticated
using (true);

drop policy if exists "app_permissions_read" on public.app_permissions;
create policy "app_permissions_read"
on public.app_permissions
for select
to authenticated
using (true);

drop policy if exists "app_role_permissions_read" on public.app_role_permissions;
create policy "app_role_permissions_read"
on public.app_role_permissions
for select
to authenticated
using (true);

drop policy if exists "app_user_roles_read_own" on public.app_user_roles;
create policy "app_user_roles_read_own"
on public.app_user_roles
for select
to authenticated
using (auth.uid() = user_id or public.is_admin());

-- Escritura solo admin.
drop policy if exists "app_roles_admin_write" on public.app_roles;
create policy "app_roles_admin_write"
on public.app_roles
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "app_roles_admin_update" on public.app_roles;
create policy "app_roles_admin_update"
on public.app_roles
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "app_roles_admin_delete" on public.app_roles;
create policy "app_roles_admin_delete"
on public.app_roles
for delete
to authenticated
using (public.is_admin());

drop policy if exists "app_permissions_admin_write" on public.app_permissions;
create policy "app_permissions_admin_write"
on public.app_permissions
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "app_permissions_admin_update" on public.app_permissions;
create policy "app_permissions_admin_update"
on public.app_permissions
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "app_permissions_admin_delete" on public.app_permissions;
create policy "app_permissions_admin_delete"
on public.app_permissions
for delete
to authenticated
using (public.is_admin());

drop policy if exists "app_role_permissions_admin_write" on public.app_role_permissions;
create policy "app_role_permissions_admin_write"
on public.app_role_permissions
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "app_role_permissions_admin_delete" on public.app_role_permissions;
create policy "app_role_permissions_admin_delete"
on public.app_role_permissions
for delete
to authenticated
using (public.is_admin());

drop policy if exists "app_user_roles_admin_write" on public.app_user_roles;
create policy "app_user_roles_admin_write"
on public.app_user_roles
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "app_user_roles_admin_delete" on public.app_user_roles;
create policy "app_user_roles_admin_delete"
on public.app_user_roles
for delete
to authenticated
using (public.is_admin());

-- Seeds (opcional): roles base.
insert into public.app_roles (name, description)
values
  ('Administrador', 'Acceso total'),
  ('Supervisor', 'Acceso operativo ampliado'),
  ('Cajero', 'Operacion de caja y facturacion')
on conflict (name) do nothing;

-- Seeds (opcional): permisos ejemplo (ajuste a sus modulos).
insert into public.app_permissions (key, description)
values
  ('facturacion.read', 'Ver facturacion'),
  ('facturacion.write', 'Crear/editar facturas'),
  ('inventario.read', 'Ver inventario'),
  ('inventario.write', 'Modificar inventario'),
  ('caja.read', 'Ver caja'),
  ('caja.write', 'Registrar movimientos de caja'),
  ('config.write', 'Cambiar configuracion')
on conflict (key) do nothing;
